[package]
authors = ["Erutuon <5840197+Erutuon@users.noreply.github.com>"]
edition = "2018"
name = "lua-function-at-line"
version = "0.1.0"

[dependencies]
full_moon = { path = "../full-moon/full-moon" }
itertools = "0.9.0"
